			<script>
			url = "fans";
			</script>            
			<div class="col s7 real" id="site-content">              
                <div class="profile-menu ">
                    <ul>
                        <li class="selected" >
                            <?= $sm['lang'][73]['text']; ?>
                        </li>                                     
                    </ul>
                </div>
				
                <div class="wall" > 
					<center>
						<h5 style="cursor:pointer;padding-top:65px;color:#666666;">
						<i class="mdi-maps-local-atm" style="color:#09c66e;font-size:166px;"></i><br><br><?= $sm['lang'][123]['text']; ?> <br>
						<?= $sm['lang'][124]['text']; ?> <b><?= $sm['user']['credits']; ?></b> <?= $sm['lang'][73]['text']; ?></h5>
					</center>
                </div>

        
            </div> 