<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html><head><title>{lang}353{/lang} $email_name</title>
</head><body topmargin='0' bottommargin='0' align='center' leftmargin='0' rightmargin='0' style='-webkit-font-smoothing: antialiased;width:100% !important;background:#FFFFFF;-webkit-text-size-adjust:none;color: #333333;font-size:16px;font-family:Helvetica Nueue, Helvetica, Arial, sans-serif;'><table class="table" align="left" width="100%" cellpadding="0" cellspacing="0" >
<tr>
<td>
<table class="table" align="center" width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial, Helvetica, sans-serif;background-color:#FFFFFF;border-top:3px solid #1dd618; text-align: left">
<tr>
<td height="20"></td>
</tr>
</table>
</td>
</tr>
<tr>
<td>
<table cellspacing="0" cellpadding="0" width="100%">
<tr>
<td style="padding-left: 10px;">
<span style="font-family: Arial; font-size: 24px;">
$user_name, {lang}354{/lang} <a href="$email_url">$email_name</a>!
</span>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td height="20"></td>
</tr>
<tr>
<td height="1" style="background: #e6e6e6; width:100%;"></td>
</tr>
<tr>
<td height="20"></td>
</tr>
<tr>
<td style="padding-left: 10px;padding-right: 10px;">
<table cellspacing="0" cellpadding="0" align="left">
<tr>
<td width="125" height="125">
<a href="$email_url" style="text-decoration: none; border: 1px solid #FFFFFF; display: block;">
<img src="$email_photo" width="125px" />
</a>
</td>
<td width="20"></td>
</tr>
</table>
<table cellpadding="0" align="left" cellspacing="0" >
<tr>
<td height="20"></td>
</tr>
<tr>
<td>
<span style="color: #333333; font-size: 13px;font-family:Arial, Helvetica, sans-serif;">
<a href="$email_url" style="color:#1155cc;white-space: nowrap; text-decoration: underline;font-weight: bold; font-size:17px;">$email_name</a>, $email_age</span>
</td>
</tr>
<tr>
<td height="5"></td>
</tr>
<tr>
<td>
<span style="color: #333333; font-size: 13px"> $email_loc</span>
</td>
</tr>
<tr>
<td height="5"></td>
</tr>
<tr>
<td>
<span style="font-size:18px;font-family:Helvetica Nueue, Helvetica, Arial, sans-serif;color:#333333;">
$email_message
</span>
</td>
</tr>
<tr>
<td height="5"></td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="padding-left: 10px;padding-right: 10px;">
<table class="table" cellspacing="0" bgcolor="#ffffff" width="100%">
<tr>
<td bgcolor="#ffffff">
<table cellpadding="0" cellspacing="0" width="100%">
<tr>
<td height="10"></td>
</tr>
<tr>
<td height="10"></td>
</tr>
<tr>
<td align="center">
<table cellspacing="0" cellpadding="0">
<tr>
<td bgcolor="#46B501" valign="middle">
<a href="$site_url" style="background:#46B501;color:#ffffff;font-size:16px;line-height:20px;text-align:center;text-decoration:none;padding:10px 15px;display:block;font-weight:bold;width:300px;">
{lang}355{/lang} $email_name
</a>
</td>
</tr>
</table>

<input type="hidden" name="receiver" value="1546191353" />
</form>
</td>
</tr>
</table>
</td>
</tr>
</table>

<tr>
<td height="20" style="border-bottom: 1px solid #CCC;"></td>
</tr>
<tr>
<td height="20"></td>
</tr>
<tr>
<td style="font-size:14px;font-family:Helvetica Nueue, Helvetica, Arial, sans-serif;color:#333333;">
{lang}356{/lang}<br />
$site_name staff!</td>
</tr>
<tr>
<td height="20" style="border-bottom: 1px solid #CCC;"></td>
</tr>
</table>
</td>
</tr>

<tr>
<td height="20"></td>
</tr>
<tr>
<td style="font-size:10px; color:#333333; padding:0 20px;">
</td>
</tr>
<tr>
<td height="10"></td>
</tr>
<tr>
<td colspan="4" width="100%" style="font-family: Arial,Helvetica,sans-serif;font-size: 11px;color: #777777;padding:0 20px;">
{lang}345{/lang} $user_name (<a href="$site_url" style="color: #1155cc;">$user_email</a>) <a href="$site_url" style="color: #1155cc;">{lang}346{/lang}</a>.
</td>
</tr>
<tr>
<td height="20"></td>
</tr>
<tr>
<td height="20" style="background-color: #f3f3f3;"></td>
</tr>
</table>
</body>
</html>