<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html><head><title>Test</title>
<style>
@media only screen and (max-width: 480px) {
body, #sexyMailBackground {
background-color: #FFFFFF !important;
}
td[class="none"] {
display: none !important;
}
td[class="spacer"] {
height: 15px;
}
td[class="p5"] {
padding: 5px !important;
}
table[class="smaller"]Â {
background-color: red !important;
width: 150px !important;
}
table[class="hide"], img[class="hide"], tr[class="hide"], td[class="hide"] {
display: none !important;
}
table[class="table"], td[class="cell"] {
border: 0 !important;
width: 300px !important;
}
td[class="cell"] img.small {
display: none;
}
table[class="onlineVersion"] {
background-color: #FFFFFF !important;
width: 300px !important;
}
table[class="onlineVersion"] tr {
background-color: #FFFFFF !important;
}
tr[class="header"] {
height: 50px;
}
td[class="logo"] {
width: 120px !important;
}
td[class="logo"] > img {
width: 110px;
padding: 5px !important;
}
tr[class="subheader"] {
height: 35px;
}
tr[class="subheader"] > td > p {
padding-left: 10px !important;
}
img[class="avatar"] {
text-align: right !important;
height: 70px !important;
width: 70px !important;
}
td[class="title"] {
padding: 10px !important;
}
td[class="title"] > p > span {
font-size: 14px !important;
}
td[class="button"] {
width: 130px;
}
table[class="sexyMailContent"] > tbody > tr > td:first-child {
padding: 5px !important;
}
td[class="icon"] {
width: 60px;
}
td[class="icon"] > img {
width: 50px !important;
}
table[class="sexyMailFooter"] {
border-spacing: 0 !important;
}
table[class="sexyMailFooter"] td[class="unsubscribe"] {
width: 280px;
padding: 10px !important;
}
}
</style>

</head><body topmargin='0' bottommargin='0' align='center' leftmargin='0' rightmargin='0' style='-webkit-font-smoothing: antialiased;width:100% !important;background:#f3f3f3;-webkit-text-size-adjust:none;color: #333333; margin: 0;padding: 0;font-size:16px;font-family:Helvetica Nueue, Helvetica, Arial, sans-serif;'><span style="display:none!important;"></span><table class="table" align="center" width="640" cellpadding="0" cellspacing="0" style="width: 640px; background: #FFFFFF;">
<tr>
<td height="25" style="background: #999; width:100%;"></td>
</tr>
<tr>
<td height="25"></td>
</tr>
<tr>
<td></td>
</tr>
<tr>
<td style="padding: 0 20px">
<center><span style="color: #333; font-size: 20px;">SMTP server is working correctly</span></center>
</td>
</tr>

<tr>
<td height="20">
</td>
</tr>
<tr>
<td valign="top" style="padding: 0 20px;">
<table cellspacing="0" cellpadding="0">
<tr>
<td>
<table cellspacing="0" cellpadding="0">

</table>

</body>
</html>