		<script>
		url = "discover";
		document.getElementById("search_filter").style.display = "block";
		</script>
		<div class="pages_maincontent_footer" style="top:20px;">
			  <div class="liked"><?= $sm['lang'][297]['text']; ?><?= $sm['lang'][298]['text']; ?>!</div><div class="disliked"><?= $sm['lang'][299]['text']; ?>!</div>
			<div class="btns"><i class="like"></i><i class="unlike"></i></div>
			<div class="discover" id="dis_photos" style="position:fixed; width:100%;"></div>
		</div>	