			<script>
			url = "discover";
			</script>              
			<div class="col s7 real" id="site-content" style="background:#e8e9ec; z-index: 100;" >                
				<div class="discover-back"></div>        
				<div class="discover-menu">
					<div class="profile-photo-back"></div>
					<div id="dis_profile_photo" class="profile-photo" data-src=""></div>                
					<h3 id="dis_name"></h3>
					<span id="dis_city"></span>
					<div class="like"><i class="mdi-action-thumb-up"></i><span id="dis_fans"></span></div>
					<div class="unlike"><i class="mdi-action-thumb-down"></i></div>                
				</div>
				<div class="discover z-depth-2" id="dis_photos">
				</div>
            </div> 