			<script>
			url = "popular";
			</script>            
			<div class="col s7 real" id="site-content">              
                <div class="profile-menu ">
                    <ul>
                        <li class="selected" >
                            <?= $sm['lang'][116]['text']; ?>
                        </li>                                     
                    </ul>
                </div>
				
                <div class="wall" > 
					<?= popularUsers(); ?>
                </div>

        
            </div> 