		<script>
		url = "matches";
		document.getElementById("navbar-title").innerHTML=site_config.name;	
		</script>	
		<div class="grey-header">
              <h2 class="grey-heading-title"><?= $sm['lang'][105]['text']; ?></h2>
        </div>		
		<?= userMatches(); ?>
		<div class="grey-header">
              <h2 class="grey-heading-title"><?= $sm['lang'][295]['text']; ?> <3</h2>
        </div>
		<?= myLikes(); ?>			
