			<?php 
			if($_GET['id'] != NULL ){
				$usid = secureEncode($_GET['id']);	
				getUserInfo($usid,1);
			}
			$profile_info = json_encode($sm['profile']);	
			echo 
			'<script>
			current_user_id = ' . $sm['profile']['id'] .';
			var profile_info = '. $profile_info  . ';	
			url = "chat";
			chatLimit = true;
			</script>';
			?>
			<div class="col s7 real" id="site-content">              
                <div class="profile-menu ">
                    <ul>
                        <li class="selected" >
                            <?= $sm['lang'][91]['text']; ?>
                        </li>                                     
                    </ul>
                </div>
				
                <div class="wall" > 
					<center>
					    <i class="mdi-action-query-builder" style="padding-top:65px;color:#666;font-size:166px;"></i>
						<h5 style="color:#333;font-size:16px;">
						<?= $sm['user']['first_name']; ?> <?= $sm['lang'][92]['text']; ?><br>
						</h5>
					
					<div class="divider"></div>	
					<p style="color:#333;font-size:16px;">
					<?= $sm['lang'][93]['text']; ?> <a href="javascript:;" data-credits="1"><?= $sm['lang'][94]['text']; ?> <?= $sm['basic']['chat']; ?> <?= $sm['lang'][95]['text']; ?></a><br>
					<? if($sm['user']['premium'] == 0){ ?>
						<?= $sm['lang'][96]['text']; ?> <a href="javascript:;" data-premium="1"><?= $sm['lang'][97]['text']; ?></a> <?= $sm['lang'][98]['text']; ?>
						<?= $sm['premium']['chat']; ?> <?= $sm['lang'][99]['text']; ?> <br>
					<? } ?>
					<?= $sm['lang'][100]['text']; ?>  <i class="mdi-social-mood"></i>
					</p>
					</center>
                </div>

        
            </div> 