		<script>
		url = "messages";
		document.getElementById("navbar-title").innerHTML="<?= $sm['lang'][297]['text']; ?>";	
		document.getElementById("mobile-new-message").style.display = "none";
		</script>         
		<ul class="list list-messages">
			<?= getUserFriendsMobile($sm['user']['id']); ?>
        </ul>
		<input type="hidden" id="moti"/>
	<div class="wdt-emoji-popup">
		<a href="#" class="wdt-emoji-popup-mobile-closer"> &times; </a>
		<div class="wdt-emoji-menu-content">
			<div id="wdt-emoji-menu-header">
				<a class="wdt-emoji-tab active" data-group-name="People"></a>
				<a class="wdt-emoji-tab" data-group-name="Nature"></a>
				<a class="wdt-emoji-tab" data-group-name="Foods"></a>
				<a class="wdt-emoji-tab" data-group-name="Activity"></a>
				<a class="wdt-emoji-tab" data-group-name="Places"></a>
				<a class="wdt-emoji-tab" data-group-name="Objects"></a>
				<a class="wdt-emoji-tab" data-group-name="Symbols"></a>
				<a class="wdt-emoji-tab" data-group-name="Flags"></a>
				<a class="wdt-emoji-tab" data-group-name="Custom"></a>
			</div>
			<div class="wdt-emoji-scroll-wrapper">
				<div id="wdt-emoji-menu-items">
					
					<h3 id="wdt-emoji-search-result-title">Search Results</h3>
					<div class="wdt-emoji-sections"></div>
					<div id="wdt-emoji-no-result">No emoji found</div>
				</div>
			</div>
			<div id="wdt-emoji-footer">
				<div id="wdt-emoji-preview">
					<span id="wdt-emoji-preview-img"></span>
					<div id="wdt-emoji-preview-text">
						<span id="wdt-emoji-preview-name"></span><br>
						<span id="wdt-emoji-preview-aliases"></span>
					</div>
				</div>

				<div id="wdt-emoji-preview-bundle">
					<span></span>
				</div>
			</div>
		</div>
	</div>		