      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Mobile apps settings
          </h1>
        </section>
		<script>aurl = 'apps';</script>
        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Android app settings</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
				<p style="padding:20px;font-size:20px;">This domain dont own Android app license , please go to <a href="http://premiumdatingscript.com" target="_blank">Premium Dating Script</a> for purchase the license and more info </p>
              </div><!-- /.box -->
			</div>
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">iOS app settings</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
				<p style="padding:20px;font-size:20px;">This domain dont own iOS app license , please go to <a href="http://premiumdatingscript.com" target="_blank">Premium Dating Script</a> for purchase the license and more info </p>
              </div><!-- /.box -->
			</div>		
		</div>	
		
		
	</section>
</div>	