      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Fake users chats
          </h1>
        </section>
		<script>aurl = 'fake';</script>
        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-md-12">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Fake users</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
				<p style="padding:20px;font-size:20px;">Your script dont have any fake user yet, please go to <a href="http://premiumdatingscript.com" target="_blank">Premium Dating Script</a> for purchase some and support </p>
              </div><!-- /.box -->
			</div>		
		</div>	
		
		
	</section>
</div>	