      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <center><h1>
            Gifts settings
          </h1><span>The price is in credits, for edit just change the number in the input it auto-update</center>
        </section>
		<script>aurl = 'gifts';</script>
        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-md-12">
                <!-- form start -->
                <form role="form" action="#" id="gift-settings">
                  <div class="box-body">	
					<?= getAdminGifts(); ?>
                  </div><!-- /.box-body -->
				  
				  <br>
                </form>
              </div><!-- /.box -->
			</div>				
	</section>
</div>	