      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
		<script>aurl = 'lang';</script>	  
        <section class="content">
          <div class="row">
            <div class="col-md-12">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Manage languages, select language for edit</h3>
                </div><!-- /.box-header -->
                  <div class="box-body">
					  <div class="row">			  
						<?= getAdminLang(); ?>
					</div>
                  </div>
              </div><!-- /.box -->
			</div>		
		</div>	
	</section>
</div>	