      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Reported users
          </h1>
        </section>
		<script>aurl = 'reports';</script>
        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Manage Reports</h3>
                  <div class="box-tools">
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                  <table class="table table-hover" id="userslist">
                    <tr>
                      <th></th>						
                      <th>ID</th>				  
                      <th>User</th>				  
                      <th>Email</th>
                      <th>City</th>
                      <th>Country</th>
                      <th>Credits</a></th>	
                      <th>Total photos</th>
                      <th></th>						  
					  <th>Reported by</th>
                    </tr>
					<?= getAdminUsersReported(); ?>
                  </table>
                </div><!-- /.box-body -->
                <div class="box-footer clearfix">
                </div>
              </div><!-- /.box -->
            </div>		  
	
		</div>	
		
		
	</section>
</div>	