      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Script Installed themes
          </h1>
        </section>
		<script>aurl = 'themes';</script>
        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-md-3">
				<?= getAdminThemesLanding(); ?>
			</div>
            <div class="col-md-3">
				<?= getAdminThemesFrontEnd(); ?>
			</div>
            <div class="col-md-3">
				<?= getAdminThemesMobile(); ?>
			</div>
            <div class="col-md-3">
				<?= getAdminThemesEmail(); ?>
			</div>		
		</div>
	<div class="row">
		<div class="col-md-6">
			<div class="box">
                <div class="box-header">
					<center>
						<h3>Badoo inspired exclusive theme</h3>
						<a href="https://premiumdatingscript.com" target="_blank" class="btn btn-success" style="background:#2B65F8">$499 buy now</a>
					</center>
                </div>		
                <center><img src="https://premiumdatingscript.com/img/badoo_screenshot.jpg" height="250px"/></center>	
              </div>			
		</div>
		<div class="col-md-6">
			<div class="box">
                <div class="box-header">
					<center>
						<h3>Tinder inspired exclusive theme</h3>
						<a href="https://premiumdatingscript.com" target="_blank" class="btn btn-success" style="background:#FE684F">$399 buy now</a>
					</center>
                </div>		
                <center><img src="https://premiumdatingscript.com/img/tinder_screenshot.jpg" height="250px"/></center>
              </div>			
		</div>		
	</div>		
	<div class="row">
		<div class="col-md-12" style="background:#f3f3f3">
			<p style="font-size:20px;padding:20px;">For get more exclusive themes check out our main site <a href="http://premiumdatingscript.com" target="_blank">Premium Dating Script</a> we will publish a new theme every month!
		</div>	
	</div>			
		
		
	</section>
</div>	