	<?
	if($_GET['id'] != ''){
		$id = secureEncode($_GET['id']);
		getUserInfo($id,8);
	}	
	?>
	  <script>aurl = 'users';</script>	
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Edit <?= $sm['edit']['name']; ?></h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <form role="form" action="#" id="site-user">
				<input type="hidden" value="edit_u" name="action" />
                  <div class="box-body">
                    <div class="form-group">
                      <label for="exampleInputEmail1">ID</label>
					  <input class="form-control" value="<?= $sm['edit']['id']; ?>" name="edit_id" readonly />
                    </div>				  
                    <div class="form-group">
                      <label for="exampleInputEmail1">Name</label>
					  <input class="form-control" value="<?= $sm['edit']['name']; ?>" name="edit_name" />
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail1">Email</label>
					  <input class="form-control" value="<?= $sm['edit']['email']; ?>" name="edit_email" />
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail1">Age</label>
					  <input class="form-control" value="<?= $sm['edit']['age']; ?>" name="edit_age" />
                    </div>					
                    <div class="form-group">
                      <label for="exampleInputPassword1">Gender</label>
						<select class="form-control" name="edit_gender" >
						<? if($sm['edit']['gender'] == 1){ ?>
							<option value="1">Male</option>						
							<option value="0">Female</option>
						<? } else { ?>
							<option value="0">Female</option>
							<option value="1">Male</option>
						<? } ?>
						</select>
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail1">City</label>
					  <input class="form-control" value="<?= $sm['edit']['city']; ?>" name="edit_city" />
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail1">Country</label>
					  <input class="form-control" value="<?= $sm['edit']['country']; ?>" name="edit_country" />
                    </div>		
                    <div class="form-group">
                      <label for="exampleInputEmail1">Credits</label>
					  <input class="form-control" value="<?= $sm['edit']['credits']; ?>" name="edit_credits" />
                    </div>	
					<? if($sm['edit']['premium_check'] != 0){ ?>
						<div class="form-group">
						  <label for="exampleInputEmail1">Premium (in days) [0 for remove premium] <?= $sm['edit']['first_name']; ?> is premium until <?= adminCheckDaysLeft($sm['edit']['premium_check']); ?></label>
						  <input class="form-control" value="" name="edit_premium" />
						</div>		
					<? } else { ?>
						<div class="form-group">
						  <label for="exampleInputEmail1">Premium (in days) - 0 for remove premium <?= $sm['edit']['first_name']; ?> is NOT premium</label>
						  <input class="form-control" value="" name="edit_premium" />
						</div>					
					<? } ?>
					<div class="form-group">
					  <label for="exampleInputEmail1">Verified - 1 = yes 0 = no</label>
					  <input class="form-control" value="<?= $sm['edit']['verified']; ?>" name="edit_verified" />
					</div>					
                    <div class="form-group">
                      <label for="exampleInputPassword1">Language</label>
						<select class="form-control" name="edit_lang" >
							<option value="<?= $sm['edit']['lang']; ?>"> <?= getCurrentLang($sm['edit']['lang']); ?> </option>
							<?= getSiteLangs($sm['config']['lang']); ?>
						</select>
                    </div>	
                    <div class="form-group">
                      <label for="exampleInputPassword1">Admin</label>
						<select class="form-control" name="edit_admin" >
						<? if($sm['edit']['admin'] == 1){ ?>
							<option value="1">Yes</option>						
							<option value="0">No</option>
						<? } else { ?>
							<option value="0">No</option>
							<option value="1">Yes</option>
						<? } ?>
						</select>
                    </div>						
                  </div><!-- /.box-body -->
                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Update <?= $sm['edit']['name']; ?></button>
                    <a href="javascript:;" data-delete-user="<?= $sm['edit']['id']; ?>" class="btn btn-danger pull-right">Delete <?= $sm['edit']['name']; ?></a>					
                  </div>
                </form>
              </div><!-- /.box -->
			</div>
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Photos</h3>
                </div><!-- /.box-header -->
                  <div class="box-body">
					  <ul class="users-list clearfix">
						<?=  getPhotosUser($sm['edit']['id']); ?>
					  </ul><!-- /.users-list -->								
                  </div><!-- /.box-body -->
              </div><!-- /.box -->
			    
			</div>
		</div>			
	</section>
</div>		