<html>
	<head>
		<title><?php echo $sm['config']['title']; ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
		<meta name="description" content="<?php echo $sm['config']['description']; ?>">
		<meta name="keywords" content="<?php echo $sm['config']['keywords']; ?>">
		<meta name="author" content="<?php echo $sm['config']['name']; ?>">		
		<noscript>		
		<link rel="stylesheet" href="<?php echo $sm['config']['theme_url_landing']; ?>/css/skel.css" />
		<link rel="stylesheet" href="<?php echo $sm['config']['theme_url_landing']; ?>/css/style.css" />
		<link rel="stylesheet" href="<?php echo $sm['config']['theme_url_landing']; ?>/css/style-wide.css" />
		</noscript>
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/jquery.min.js"></script>
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/jquery.dropotron.min.js"></script>
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/jquery.scrollgress.min.js"></script>
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/skel.min.js"></script>
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/skel-layers.min.js"></script>
		<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places&key=<?= siteConfig('google_maps'); ?>"></script>	
		<style>
		/* Preloader */
		#preloader {
			position: fixed;
			top:0;
			left:0;
			right:0;
			bottom:0;
			background-color:#fff; /* change if the mask should have another color then white */
		  height:100%;
		  width:100%;
			z-index:99; /* makes sure it stays on top */
		}

		#status {
			width:200px;
			height:200px;
			position:absolute;
			left:50%; /* centers the loading animation horizontally one the screen */
			top:50%; /* centers the loading animation vertically one the screen */
			background-image:url(<?php echo $sm['config']['theme_url_landing']; ?>/images/status.gif); /* path to your loading animation */
			background-repeat:no-repeat;
			background-position:center;
			margin:-100px 0 0 -100px; /* is width and height divided by two */
		}
		</style>
		<?php

		$site_config = json_encode($sm['config']);
		$site_lang = json_encode($sm['lang']);
		$user_info = json_encode($sm['user']);
		$filter_age = 0;
		echo 
		'<script>
		var url;
		var mobile = false;
		var site_config = '. $site_config  . ';
		var site_lang = '. $site_lang  . ';
		var user_info = '. $user_info  . ';
		function request_source(){
			return \'' . $sm['config']['ajax_path'] . '\';
		}
		function site_title(){
			return \'' . $sm['config']['title'] . '\';
		}	
		function theme_source(){
			return \'' . $sm['config']['theme_url'] . '\';
		}
		function site_url(){
			return \'' . $sm['config']['site_url'] . '\';
		}	
		function user_id(){
			return \'' . $sm['user']['id'] . '\';
		}
		var current_user_id = 0;
		var user_name;	
		</script>';
		?>	
		<script>
		function detect_device() {
			var w = window,
				d = document,
				e = d.documentElement,
				g = d.getElementsByTagName('body')[0],
				x = w.innerWidth || e.clientWidth || g.clientWidth,
				y = w.innerHeight|| e.clientHeight|| g.clientHeight;
			var isiPhone = 		navigator.userAgent.toLowerCase().indexOf("iphone");
			var isiPad = 		navigator.userAgent.toLowerCase().indexOf("ipad");
			var isiPod = 		navigator.userAgent.toLowerCase().indexOf("ipod");
			var isiAndroid = 	navigator.userAgent.toLowerCase().indexOf("android");
			if(isiPhone > -1 || isiPad > -1 || isiPod > -1 || isiAndroid > -1 && mobile == false){
				window.location='mobile.php?page=login';
			}
			if(x <= 800 && mobile == false){
				window.location='mobile.php?page=index';	
			}			

		}
		detect_device();
		window.onresize = function() {
			var w = window,
				d = document,
				e = d.documentElement,
				g = d.getElementsByTagName('body')[0],
				x = w.innerWidth || e.clientWidth || g.clientWidth,
				y = w.innerHeight|| e.clientHeight|| g.clientHeight;	
				
			if(x <= 800 && mobile == false){
				window.location='mobile.php?page=index';	
			}
			if(x > 801 && mobile == true){
				window.location='index.php?page=index';	
			}		
		};
		</script>
		<?= siteConfig('css'); ?>
	</head>
	<body class="landing">
			<div id="preloader">
				<div id="status">&nbsp;</div>
			</div>	
			<header id="header" class="alt">
				<h1><a href="javascript:;"><?= $sm['config']['name']; ?>    </a> <?= $sm['lang'][0]['text']; ?></h1>
				<nav id="nav">
				  <ul>
						<li>
							<a href="javascript:;" class="icon fa-angle-down"><span class="icon fa-globe"></span></a>
							<ul> 
                            <table>
                            <tr>
								<?= getSiteLangsIndex(0,6); ?>                          
                            </tr>
								<?= getSiteLangsIndex(6,6); ?>  
                            <tr>                        
                            </tr>
								<?= getSiteLangsIndex(12,6); ?>
                            <tr>                           
                            </tr>
								<?= getSiteLangsIndex(18,6); ?>
                            <tr>                          
                            </tr> 
								<?= getSiteLangsIndex(24,6); ?>
                            <tr>                          
                            </tr>
								<?= getSiteLangsIndex(30,6); ?>
                            <tr>                           
                            </tr>
								<?= getSiteLangsIndex(36,6); ?>
                            <tr>                           
                            </tr>
								<?= getSiteLangsIndex(42,6); ?>
                            <tr>                          
                            </tr>  
							
                            </table>                           
                       		</ul>
						</li>
						<li><a href="javascript:;" id="go-to-register-form" class="button special"><?= $sm['lang'][8]['text']; ?></a></li>						
						<li><a href="javascript:;" data-login="true" class="button special"><?= $sm['lang'][1]['text']; ?></a></li>
					</ul>
				</nav>
			</header>

			<section id="banner" >
				<div class="show-mobile">
                    <h2 ><?= $sm['config']['name']; ?></h2>
                    <p><?= $sm['lang'][2]['text']; ?><br>
					<?= $sm['lang'][3]['text']; ?><br> <?= $sm['lang'][4]['text']; ?><br>
					<span style="font-weight:600"><?= $sm['lang'][5]['text']; ?></span></p>				
					<div class="appbuttons">
						<a href="javascript:;" class="appbutton google"> <span><strong><?= $sm['lang'][6]['text']; ?></strong></a>
						<a href="javascript:;" class="appbutton iphone"> <span><strong><?= $sm['lang'][6]['text']; ?></strong></a>
					</div>
				</div>
            	<div id="main-message" class="hide-mobile" >
                    <h2 style="font-weight:600"><?= $sm['config']['name']; ?></h2>
                    <p><?= $sm['lang'][2]['text']; ?></p>
                    <ul class="actions">
						<li><span><?= $sm['lang'][7]['text']; ?>:</span></li>
						<? if(siteConfig('fb_app_id') != '') { ?>
						<li>
							<a href="index.php?social=fb" class="facebook-button">
								<span class="icon fa-facebook-square" style="font-size:30px;"></span>
							</a>
						</li>
						<? } if(siteConfig('twitter_key') != ''){ ?>
						<li>
							<a href="index.php?social=twitter" class="twitter-button">
								<span class="icon fa-twitter-square" style="font-size:30px;"></span>
							</a>
						</li>	
						<? } if(siteConfig('google_key') != ''){  ?>
						<li>
							<a href="index.php?social=google" class="google-button">
								<span class="icon fa-google-plus" style="font-size:30px;"></span>
							</a>
						</li>	
						<? } if(siteConfig('instagram_key') != ''){ ?>
						<li>
							<a href="index.php?social=instagram" class="instagram-button">
								<span class="icon fa-instagram" style="font-size:30px;"></span>
							</a>
						</li>	
						<? } ?>
                    </ul>
                </div>
                
            	<div id="login-form" style="display:none;">
                    <h2><?= $sm['config']['name']; ?></h2>
                    <p><?= $sm['lang'][9]['text']; ?></p>
                    <form id="login" action="#">
					<input type="hidden" value="login" name="action" />
                        <div style="width:98%;margin:0 auto;">
                            <center>                                        
                                <div class="4u 12u(mobilep)">
                                    <input type="email" name="login_email" id="login_email" required style="color:#333; font-weight:600;" placeholder="<?= $sm['lang'][10]['text']; ?>" />
                                </div><br>                  
                                <div class="4u 12u(mobilep)">
                                    <input type="password" name="login_pass" id="login_pass" style="color:#333; font-weight:600;" placeholder="<?= $sm['lang'][11]['text']; ?>" />
									<input type="hidden" name="login_dID" value="0" />
                                </div>
								<div class="4u 12u(mobilep)" style="text-align:right; font-size:14px; " ><a href="javascript:;" id="recover-pwd"><?= $sm['lang'][12]['text']; ?></a></div>	
								<div class="12u 12u(mobilep)" style=" font-size:22px; font-weight:600;" id="login-error"></div>									
                            </center>                        
                        </div>
                    </form>  
                    <ul class="actions">              
                        <li><a href="#" class="sign-button" id="login-now"><?= $sm['lang'][13]['text']; ?></a></li>
                    </ul>
                </div> 

            	<div id="recover-form" style="display:none;">
                    <h2><?= $sm['config']['name']; ?></h2>
                    <p><?= $sm['lang'][14]['text']; ?></p>
                    <form id="recover" action="#">
					<input type="hidden" value="recover" name="action" />
                        <div style="width:98%;margin:0 auto;">
                            <center>                                        
                                <div class="4u 12u(mobilep)">
                                    <input type="email" name="recover_email" id="recover_email" style="color:#333; font-weight:600;" required placeholder="<?= $sm['lang'][10]['text']; ?>" />
                                </div><br>         	
								<div class="12u 12u(mobilep)" style=" font-size:22px; font-weight:600;" id="recover-error"></div>									
                            </center>                        
                        </div>
                    </form>  
                    <ul class="actions">              
                        <li><a href="#" class="sign-button" id="recover-now"><?= $sm['lang'][15]['text']; ?></a></li>
                    </ul>
                </div> 				
			</section>
                       
			<section id="main" class="container hide-mobile" >
				<section class="box special features" style="margin-top:10px;" >
					<div class="features-row">
						<section>                       
							<span class="icon major fa-comment-o accent2"></span>
							<h3><?= $sm['lang'][16]['text']; ?></h3>
							<p><?= $sm['lang'][17]['text']; ?></p>                          
						</section>
						<section>                       
							<span class="icon major fa-video-camera accent2"></span>
							<h3><?= $sm['lang'][18]['text']; ?></h3>
							<p><?= $sm['lang'][19]['text']; ?></p>
						</section>
					</div>
					<div class="features-row">
					  <section>
							<span class="icon major fa-map-marker accent2"></span>
							<h3><?= $sm['lang'][20]['text']; ?></h3>
							<p><?= $sm['lang'][21]['text']; ?></p>
						</section>
						<section>                        
							<span class="icon major fa-heart-o accent2"></span>
							<h3><?= $sm['lang'][22]['text']; ?></h3>
							<p><?= $sm['lang'][23]['text']; ?></p>
						</section>
						<div id="ads" style="position:relative;top:30px;">
							<center>
								<?= siteConfig('ads'); ?>
							</center>						
						</div>
					</div>
				</section>
			</section>
            
			<section id="cta" class="hide-mobile">

				<h2><?= $sm['lang'][24]['text']; ?></h2>
				<p><?= $sm['lang'][25]['text']; ?></p>
				<form method="post" action="#" id="register">
					<div class="row uniform 50%">
                        <? if($sm['config']['fb_app_ok'] == 1 ){ ?>
							<div class="12u 12u(mobilep)">
								<a href="index.php?social=fb" class="facebook-button" style="margin-right:20px;">
									<span class="icon fa-facebook-square" style="font-size:30px;"></span>
								</a>
								<a href="index.php?social=twitter" class="twitter-button" style="margin-right:20px;">
									<span class="icon fa-twitter-square" style="font-size:30px;"></span>
								</a>
								<a href="index.php?social=google" class="google-button" style="margin-right:20px;">
									<span class="icon fa-google-plus" style="font-size:30px;"></span>
								</a>
								<a href="index.php?social=instagram" class="instagram-button">
									<span class="icon fa-instagram" style="font-size:30px;"></span>
								</a>								
							</div>
						<? } ?>		
						<div class="3u 4u(mobilep) hide-mobile" style="text-align:left; line-height:250%; font-size:18px;">
							<?= $sm['lang'][26]['text']; ?>
						</div>                      
						<div class="9u 12u(mobilep)">
							<input type="text" name="name" maxlength="18" id="name" required placeholder="<?= $sm['lang'][27]['text']; ?>" />
						</div>
						<div class="3u 4u(mobilep) hide-mobile" style="text-align:left; line-height:250%; font-size:18px;">
							<?= $sm['lang'][28]['text']; ?>
						</div>                      
						<div class="9u 12u(mobilep)">
							<input type="email" name="email" required id="email" placeholder="<?= $sm['lang'][10]['text']; ?>" />
						</div>
						<div class="3u 4u(mobilep) hide-mobile" style="text-align:left; line-height:250%; font-size:18px;">
							<?= $sm['lang'][29]['text']; ?>
						</div>                      
						<div class="9u 12u(mobilep)">
							<input type="password" name="pass" id="pass" required placeholder="<?= $sm['lang'][11]['text']; ?>" />
						</div>                                                
						<div class="3u 4u(mobilep) hide-mobile" style="text-align:left; line-height:250%; font-size:18px;">
							<?= $sm['lang'][30]['text']; ?>
						</div>                        
						<div class="3u 4u(mobilep)">
							<select name="day" style="cursor:pointer;" id="day" placeholder="<?= $sm['lang'][31]['text']; ?>">
								<?= date_dropdown(1); ?>
                            </select>
						</div>  
						<div class="3u 4u(mobilep)">
							<select name="month" style="cursor:pointer;" id="month" placeholder="<?= $sm['lang'][31]['text']; ?>">						
							<?= date_dropdown(0,1); ?>
							</select>							
						</div>  
						<div class="3u 4u(mobilep)">
							<select name="year" style="cursor:pointer;" id="year" placeholder="<?= $sm['lang'][31]['text']; ?>">						
							<?= date_dropdown(0,0,1); ?>
							</select>
						</div>
                        
						<div class="3u 3u(mobilep) hide-mobile" style="text-align:left; line-height:250%; font-size:18px;">
							<?= $sm['lang'][32]['text']; ?>
						</div>                      
						<div class="9u 12u(mobilep)">
							<input type="text" name="loc" id="loc" required placeholder="<?= $sm['lang'][33]['text']; ?>" />
						</div>
                        
						<div class="3u 3u(mobilep) hide-mobile" style="text-align:left; line-height:250%; font-size:18px;">
							<?= $sm['lang'][34]['text']; ?>
						</div>                      
						<div class="9u 12u(mobilep)">
							<select name="gender" style="cursor:pointer;" id="gender" placeholder="<?= $sm['lang'][31]['text']; ?>">
                            	<option value="1" style="color:#000;"><?= $sm['lang'][35]['text']; ?></option>
                                <option value="2" style="color:#000;"><?= $sm['lang'][36]['text']; ?></option>
                            </select>
						</div>
                        
						<div class="3u 3u(mobilep) hide-mobile" style="text-align:left; line-height:250%; font-size:18px;">
							<?= $sm['lang'][37]['text']; ?>
						</div>                      
						<div class="9u 12u(mobilep)">
							<select name="looking" style="cursor:pointer;" id="looking" placeholder="<?= $sm['lang'][31]['text']; ?>">
                            	<option value="2" style="color:#000;"><?= $sm['lang'][38]['text']; ?></option>
                                <option value="1" style="color:#000;"><?= $sm['lang'][39]['text']; ?></option>
                                <option value="3" style="color:#000;"><?= $sm['lang'][40]['text']; ?></option>                                
                            </select>
						</div>
						<input type="hidden" value="register" name="action" />
						<input type="hidden" name="city" id="locality" />
						<input type="hidden" name="country" id="country"  />
						<input type="hidden" name="lat" id="lat" />
						<input type="hidden" name="lng" id="lng"  />						
                        <div class="12u 12u(mobilep)" style=" font-size:22px; font-weight:600;" id="error"></div>						
                                                                                                                        
						<div class="12u 12u(mobilep)">
							<a href="javascript:;" class="sign-button" id="create-acc" style="width:100%;"><?= $sm['lang'][41]['text']; ?></a>
						</div>
                        
                        <div class="12u 12u(mobilep)">
							<?= $sm['lang'][42]['text']; ?> <a href="<?= $sm['config']['site_url']; ?>/index.php?page=tac" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=tac','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][43]['text']; ?> </a> <?= $sm['lang'][44]['text']; ?> 
							<a href="<?= $sm['config']['site_url']; ?>/index.php?page=pp" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=pp','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][45]['text']; ?></a>
                        </div>  
                                                
					</div>
				</form>
			</section>			
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/js/init.js"></script>
		<script type="text/javascript">
			//<![CDATA[
				$(window).load(function() { // makes sure the whole site is loaded
					$('#status').fadeOut(); // will first fade out the loading animation
					$('#preloader').delay(350).fadeOut('slow'); // will fade out the white DIV that covers the website.
					$('body').delay(350).css({'overflow':'visible'});
					$('body').keyup(function(e) {
								switch (e.keyCode) {
									case 13: // Enter
										$('#login-now').click();
									break;
								}
						});						
				})
			//]]>
		</script> 	
		<?= siteConfig('js'); ?>		
	</body>
</html>