			<script>
			url = "terms";
			</script>            
			<div class="col s7 real" id="site-content">              
                <div class="profile-menu ">
                    <ul>
                        <li class="selected" >
                            <?= $sm['lang'][103]['text']; ?>
                        </li>                                     
                    </ul>
                </div>
				
                <div class="wall" > 
					<?= siteConfig('terms'); ?>
                </div>
            </div> 