<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html><head><title>{lang}361{/lang} $site_name!</title>
<style>
@media only screen and (max-width: 480px) {
body, #sexyMailBackground {
background-color: #FFFFFF !important;
}
td[class="none"] {
display: none !important;
}
td[class="spacer"] {
height: 15px;
}
td[class="p5"] {
padding: 5px !important;
}
table[class="smaller"]Â {
background-color: red !important;
width: 150px !important;
}
table[class="hide"], img[class="hide"], tr[class="hide"], td[class="hide"] {
display: none !important;
}
table[class="table"], td[class="cell"] {
border: 0 !important;
width: 300px !important;
}
td[class="cell"] img.small {
display: none;
}
table[class="onlineVersion"] {
background-color: #FFFFFF !important;
width: 300px !important;
}
table[class="onlineVersion"] tr {
background-color: #FFFFFF !important;
}
tr[class="header"] {
height: 50px;
}
td[class="logo"] {
width: 120px !important;
}
td[class="logo"] > img {
width: 110px;
padding: 5px !important;
}
tr[class="subheader"] {
height: 35px;
}
tr[class="subheader"] > td > p {
padding-left: 10px !important;
}
img[class="avatar"] {
text-align: right !important;
height: 70px !important;
width: 70px !important;
}
td[class="title"] {
padding: 10px !important;
}
td[class="title"] > p > span {
font-size: 14px !important;
}
td[class="button"] {
width: 130px;
}
table[class="sexyMailContent"] > tbody > tr > td:first-child {
padding: 5px !important;
}
td[class="icon"] {
width: 60px;
}
td[class="icon"] > img {
width: 50px !important;
}
table[class="sexyMailFooter"] {
border-spacing: 0 !important;
}
table[class="sexyMailFooter"] td[class="unsubscribe"] {
width: 280px;
padding: 10px !important;
}
}
</style>

</head><body topmargin='0' bottommargin='0' align='center' leftmargin='0' rightmargin='0' style='-webkit-font-smoothing: antialiased;width:100% !important;background:#f3f3f3;-webkit-text-size-adjust:none;color: #333333; margin: 0;padding: 0;font-size:16px;font-family:Helvetica Nueue, Helvetica, Arial, sans-serif;'><span style="display:none!important;">{lang}362{/lang} . {lang}363{/lang}.</span><table class="table" align="center" width="640" cellpadding="0" cellspacing="0" style="width: 640px; background: #FFFFFF;">
<tr>
<td height="5" style="background: #9c00e5; width:100%;"></td>
</tr>
<tr>
<td height="20"></td>
</tr>
<tr>
<td></td>
</tr>
<tr>
<td style="padding: 0 20px">
<span style="color: #870bc8; font-size: 20px;">
{lang}361{/lang}, $user_name!</span>
</td>
</tr>
<tr>
<td height="20">
</td>
</tr>
<tr>
<td valign="top" style="padding: 0 20px;">
<table cellspacing="0" cellpadding="0">
<tr>
<td>
<table cellspacing="0" cellpadding="0">
<tr>
<td>
<table cellspacing="0" cellpadding="0">
<tr>
<td bgcolor="#46B501" valign="middle" style="background:#46B501; border-bottom:3px solid #336600;border-radius:3px;-moz-border-radius:3px;-webkit-border-radius:3px;">
<a href="$site_url" style="color:#ffffff;font-size:16px;line-height:20px;text-decoration:none;padding:10px 15px;display:block;font-weight:bold;white-space:nowrap;">
{lang}379{/lang} $site_name
</span>
</a>
</td>
</tr>
</table>
</td>
<td width="20">
</td>
<td style="font-size: 14px">
<strong>{lang}366{/lang}:</strong> 50.736 {lang}367{/lang}.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td height="20"></td>
</tr>
<tr>
<td height="1" colspan="5" style="border-top: 1px solid #CCCCCC; width:100%;"></td>
</tr>
<tr>
<td height="20"></td>
</tr>
<tr>
<td colspan="5">
<table class="sexyMailContent" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td valign="top" style="padding: 0 20px;" bgcolor="#FFFFFF">
<table>
<tr valign="top">
<td width="70" align="center" style="text-align:  left " valign="middle" class="icon">
<img src="$site_email/img/search.jpg" alt="" align="center" />
</td>
<td valign="top">
<p>
<span style="font-size: 14px;font-family:Arial, Helvetica, sans-serif; color: #515151;">
{lang}369{/lang} : <a href="$site_url" style="font-size: 14px;font-family:Arial, Helvetica, sans-serif; color: #1155cc;">{lang}370{/lang}</a>
</span>
</p>
</td>
</tr>
<tr>
<td colspan="2" height="10" class="spacer"></td>
</tr>
<tr>
<td colspan="2" height="10" style="border-top: 1px solid #EFEFEF" class="spacer"></td>
</tr>
<tr valign="top">
<td width="70" align="center" style="text-align:  left " valign="middle" class="icon">
<img src="$site_email/img/photos.jpg" alt="" align="center" />
</td>
<td valign="top">
<p>
<span style="font-size: 14px;font-family:Arial, Helvetica, sans-serif; color: #515151;">
{lang}371{/lang}
<a href="$site_url" style="font-size: 14px;font-family:Arial, Helvetica, sans-serif; color: #1155cc;">
{lang}372{/lang}
</a>
</span>
</p>
</td>
</tr>
<tr>
<td colspan="2" height="10" class="spacer"></td>
</tr>

<tr>
<td colspan="2" height="10" style="border-top: 1px solid #EFEFEF" class="spacer"></td>
</tr>
<tr valign="top">
<td width="70" align="center" style="text-align:  left " valign="middle" class="icon">
<img src="$site_email/img/friends.jpg" alt="" align="center" />
</td>
<td valign="top">
<span style="font-size: 14px;font-family:Arial, Helvetica, sans-serif; color: #515151;">
{lang}373{/lang}
<a href="$site_url" style="font-size: 14px;font-family:Arial, Helvetica, sans-serif; color: #1155cc;">{lang}374{/lang}</a>
</span>
</td>
</tr>
<tr>
<td colspan="2" height="10" class="spacer"></td>
</tr>
</table>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td colspan="5" style="padding:0 20px;">
<table width="100%" style="border-radius: 5px; border:1px solid #B1B1B1; background: #EEEEEE;">
<tr>
<td>
<table width="100%" cellspacing="10">
<tr>
<td>
<span style="font-size: 15px;color:#515151;">
<strong>{lang}375{/lang}</strong><br />
<strong>{lang}376{/lang}: $user_email</strong><br />
<strong>{lang}377{/lang}: $user_password</strong><br /><br />
{lang}378{/lang}
</span>
</td>
</tr>
</table>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td height="20" style="border-bottom: 1px solid #CCC;"></td>
</tr>
<tr>
<td height="20"></td>
</tr>
<tr>
<td style="font-size:14px;font-family:Helvetica Nueue, Helvetica, Arial, sans-serif;color:#333333;">
{lang}356{/lang}<br />
$site_name staff!</td>
</tr>
<tr>
<td height="20" style="border-bottom: 1px solid #CCC;"></td>
</tr>
</table>
</td>
</tr>

<tr>
<td height="20"></td>
</tr>
<tr>
<td style="font-size:10px; color:#333333; padding:0 20px;">
</td>
</tr>
<tr>
<td height="10"></td>
</tr>
<tr>
<td colspan="4" width="100%" style="font-family: Arial,Helvetica,sans-serif;font-size: 11px;color: #777777;padding:0 20px;">
{lang}345{/lang} $user_name (<a href="$site_url" style="color: #1155cc;">$user_email</a>) <a href="$site_url" style="color: #1155cc;">{lang}346{/lang}</a>.
</td>
</tr>
<tr>
<td height="20"></td>
</tr>
<tr>
<td height="20" style="background-color: #f3f3f3;"></td>
</tr>
</table>
</body>
</html>