<!DOCTYPE html>
<html>
<head>
<title><?php echo $sm['config']['title']; ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta name="description" content="<?php echo $sm['config']['description']; ?>"/>
<meta name="keywords" content="<?php echo $sm['config']['keywords']; ?>"/>
<meta name="author" content="<?php echo $sm['config']['name']; ?>"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<link rel="stylesheet" type="text/css" href="<?php echo $sm['config']['theme_url_mobile']; ?>/css/normalize.css">
<link rel="stylesheet" type="text/css" href="<?php echo $sm['config']['theme_url_mobile']; ?>/css/framework.css">
<link rel="stylesheet" type="text/css" href="<?php echo $sm['config']['theme_url_mobile']; ?>/css/sm.css">
<link rel="stylesheet" type="text/css" href="<?php echo $sm['config']['theme_url_mobile']; ?>/css/style.css">
<link rel="stylesheet" type="text/css" href="<?php echo $sm['config']['theme_url']; ?>/css/sweet-alert.css">
<link rel="stylesheet" href="<?php echo $sm['config']['theme_url']; ?>/css/scroller.css"/>    
<link href="<?php echo $sm['config']['theme_url']; ?>/css/fbphotobox.css" rel="stylesheet" type="text/css" /> 
<script src="<?php echo $sm['config']['theme_url_mobile']; ?>/js/webfont.js"></script>
<script>
WebFont.load({
  google: {
	families: ["Montserrat:400,700","Material-Design-Icons"]
  }
});
</script>
<script type="text/javascript" src="<?php echo $sm['config']['theme_url_mobile']; ?>/js/modernizr.js"></script>
<link href="<?php echo $sm['config']['theme_url_mobile']; ?>/css/ionicons.min.css" rel="stylesheet" type="text/css" />
</head>  
<?php

$site_config = json_encode($sm['config']);
$site_prices = json_encode($sm['price']);
$account_basic = json_encode($sm['basic']);
$account_premium = json_encode($sm['premium']);
$site_lang = json_encode($sm['lang']);
$user_info = json_encode($sm['user']);
$filter_age = 0;
$app_user = 0;
$app_user = secureEncode($_GET['dID']);
echo 
'<script>
var url;
var app_user = 0;
app_user = "'. $app_user  . '";

var mobile = true;
var site_config = '. $site_config  . ';
var site_prices = '. $site_prices  . ';
var account_basic = '. $account_basic  . ';
var account_premium = '. $account_premium  . ';
var site_lang = '. $site_lang  . ';
var user_info = '. $user_info  . ';
function request_source(){
	return \'' . $sm['config']['ajax_path'] . '\';
}
function site_title(){
	return \'' . $sm['config']['title'] . '\';
}	
function theme_source(){
	return \'' . $sm['config']['theme_url'] . '\';
}
function site_url(){
	return \'' . $sm['config']['site_url'] . '\';
}	
function user_id(){
	return \'' . $sm['user']['id'] . '\';
}
var current_user_id = 0;
var user_name;	
</script>';
?>
</head>
<body>
 <section class="w-section mobile-wrapper">

    <div class="page-content" >
      <div class="w-nav navbar" style="background:#42709E" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
        <div class="w-container">
          <div class="wrapper-mask" data-ix="menu-mask"></div>
          <div class="navbar-title" style="color:#fff"><?= $sm['lang'][24]['text']; ?></div>
          <a class="w-inline-block navbar-button" style="color:#fff" href="mobile.php?page=login" data-load="1">
            <div class="navbar-button-icon icon ion-ios-close-empty"></div>
          </a>
        </div>
      </div>	
      <div class="body">
	   <div class="padding" style="background:none">
          <div class="w-form">
				<div id="cpp" style="position:absolute;left:35%;top:70px;width:120px;height:120px;border-radius:15px;cursor:pointer;background-color:#e1e1e1;background-size:cover;background-repeat: no-repeat;background-position: top center;background-image: url(<?php echo $sm['config']['theme_url_mobile']; ?>/images/photo.png);border:1px solid #bcbcbc;">
					
				</div>							
				<div id="cpp2" style="position:absolute;left:24%;top:158px;width:120px;border-radius:15px;padding:5px;text-align:center;background:none;color:#333;cursor:pointer;">
						
				</div>		  
            <form id="register" action="#" style="padding-top:145px">
			
              <div>
                <label class="label-form" for="email-field"><?= $sm['lang'][26]['text']; ?></label>
                <input class="w-input input-form"  type="text"  name="name" placeholder="<?= $sm['lang'][27]['text']; ?>"  required="required" >
                <div class="separator-fields"></div>
              </div>
			  
            <div class="w-clearfix">
              <div class="row-input-list w30 left">
                <label class="label-form" for="birthday-field"><?= $sm['lang'][272]['text']; ?></label>
                <input class="w-input input-form" id="birthday-field" type="text" maxlength="2" name="day" placeholder="DD" required="required">
                <div class="separator-fields"></div>
              </div>
              <div class="row-input-list w30">
                <label class="label-form" for="birthday-field"><?= $sm['lang'][273]['text']; ?></label>
                <input class="w-input input-form" id="birthday-field" type="text" maxlength="2" name="month" placeholder="MM" required="required">
                <div class="separator-fields"></div>
              </div>
              <div class="row-input-list w30">
                <label class="label-form" for="birthday-field"><?= $sm['lang'][274]['text']; ?></label>
                <input class="w-input input-form" id="birthday-field" type="text" maxlength="4" name="year" placeholder="YYYY" required="required">
                <div class="separator-fields"></div>
              </div>			  
            </div>
			 
            <div class="row-input-list">
              <label class="label-form" for="birthday-field"><?= $sm['lang'][32]['text']; ?></label>
              <div class="block-input-combined">
                <input class="w-input input-form left" id="loc" type="text" name="loc" placeholder="<?= $sm['lang'][33]['text']; ?>" required="required">
                <a class="w-inline-block right-input-icon color" href="#">
                  <div class="icon ion-ios-location"></div>
                </a>
              </div>
              <div class="separator-fields"></div>
            </div>	

            <div class="row-input-list">
              <div class="w-clearfix input-form one-line">
                <label class="label-form middle" for="email"><?= $sm['lang'][34]['text']; ?></label>
                <div class="w-clearfix radios-container">
                  <div class="w-radio w-clearfix radio-button">
                    <div class="radio-bullet-replacement"></div>
                    <input class="w-radio-input radio-bullet" id="node-9" type="radio" name="gender" required="required" value="1" >
                    <label class="w-form-label" for="node-9"><?= $sm['lang'][35]['text']; ?></label>
                  </div>
                  <div class="w-radio w-clearfix radio-button">
                    <div class="radio-bullet-replacement "></div>
                    <input class="w-radio-input radio-bullet" id="node-6" type="radio" name="gender" value="2" >
                    <label class="w-form-label" for="node-6"><?= $sm['lang'][36]['text']; ?></label>
                  </div>
                </div>
              </div>
              <div class="separator-fields"></div>
            </div>

            <div class="row-input-list">
              <div class="w-clearfix input-form one-line">
                <label class="label-form middle" for="email"><?= $sm['lang'][37]['text']; ?></label>
                <div class="w-clearfix radios-container">
                  <div class="w-radio w-clearfix radio-button">
                    <div class="radio-bullet-replacement"></div>
                    <input class="w-radio-input radio-bullet" id="node-11" type="radio" name="looking" required="required" value="2" >
                    <label class="w-form-label" for="node-11"><?= $sm['lang'][38]['text']; ?></label>
                  </div>
                  <div class="w-radio w-clearfix radio-button">
                    <div class="radio-bullet-replacement "></div>
                    <input class="w-radio-input radio-bullet" id="node-12" type="radio" name="looking" value="1" >
                    <label class="w-form-label" for="node-12"><?= $sm['lang'][39]['text']; ?></label>
                  </div>
                </div>
              </div>
              <div class="separator-fields"></div>
            </div>				
			 
			  <div class="separator-button-input"></div>			  
			  
              <div>
                <label class="label-form" for="email-field"><?= $sm['lang'][28]['text']; ?></label>
                <input class="w-input input-form"  type="email"  name="email"  required="required" placeholder="<?= $sm['lang'][10]['text']; ?>">
                <div class="separator-fields"></div>
              </div>
			  
              <div>
                <label class="label-form" for="email"><?= $sm['lang'][29]['text']; ?></label>
                <div class="w-clearfix block-input-combined">
                  <input class="w-input input-form left" type="password"  name="pass" required="required" placeholder="<?= $sm['lang'][11]['text']; ?>" >
                </div>
				<div class="w-form-fail" id="error" ></div>			  				
                <div class="separator-button-input"></div>
              </div>
		  
			<input type="hidden" id="profilePhoto" value="" name="photo" />
			<input type="hidden" id="profileThumb" value="" name="thumb" />	
			<input type="hidden" id="profilePrivate" value="" name="private" />				
			<input type="hidden" value="register_mobile" name="action" />
			<input type="hidden" name="city" id="locality" />
			<input type="hidden" name="country" id="country"  />
			<input type="hidden" name="lat" id="lat" />
			<input type="hidden" name="lng" id="lng"  />
			<input type="hidden" name="dID" value="<?= $app_user; ?>"  />			
              <input class="w-button action-button green" type="submit" id="create-acc" value="<?= $sm['lang'][41]['text']; ?>" data-wait="Please wait...">
              <div class="separator-button"></div>
			<center><?= $sm['lang'][42]['text']; ?> <a href="<?= $sm['config']['site_url']; ?>/index.php?page=tac" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=tac','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][43]['text']; ?> </a> <?= $sm['lang'][44]['text']; ?> 
			<a href="<?= $sm['config']['site_url']; ?>/index.php?page=pp" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=pp','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][45]['text']; ?></a></center>
            </form>
			<form enctype="multipart/form-data" name='imageform' style="display:none" role="form" id="add-photos-form2" method="post" action="<?php echo $sm['config']['site_url']; ?>/assets/sources/regImage.php">                  
				<input type="file" name="photos[]" accept="image/*"  id="add-photos-file2" multiple="false"  />
			</form>				
          </div>
		 </div>
      </div>
    </div>
    <div class="page-content loading-mask" id="new-stack">
      <div class="loading-icon">
        <div class="navbar-button-icon icon ion-load-d"></div>
      </div>
    </div>
    <div class="shadow-layer"></div>
  </section>

 
<script src="<?php echo $sm['config']['theme_url']; ?>/js/jquery-2.1.1.js"></script>
<script src="<?php echo $sm['config']['theme_url']; ?>/js/jquery.form.min.js"></script>
<script src="<?php echo $sm['config']['theme_url_mobile']; ?>/js/fastclick.js"></script>
<script src="<?php echo $sm['config']['theme_url']; ?>/js/materialize.js"></script>
<script src="<?php echo $sm['config']['theme_url']; ?>/js/fbphotobox.js"></script>
<script src="<?php echo $sm['config']['theme_url']; ?>/js/scroller.js"></script> 
<script src="<?php echo $sm['config']['theme_url']; ?>/js/sweet-alert.js"></script> 
<script src="<?php echo $sm['config']['theme_url']; ?>/js/peer.js"></script> 
<script src="<?php echo $sm['config']['theme_url']; ?>/js/galleria-1.4.2.min.js"></script> 
<script src="<?php echo $sm['config']['theme_url']; ?>/js/jquery.preload.js"></script> 
<script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
<script src="//cdn.jsdelivr.net/velocity/1.2.2/velocity.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places&key=<?= siteConfig('google_maps'); ?>"></script>
<script type="text/javascript" src="<?php echo $sm['config']['theme_url_mobile']; ?>/js/framework.js"></script>	
<script type="text/javascript" src="<?php echo $sm['config']['theme_url_mobile']; ?>/js/mobile.js"></script>
